### ISSUE TITLE
Can we deprecate this?

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-brand-images#14]
We need to review the Image Service logs to see how and where these are used. It feels like a grab-bag of random images that could live elsewhere.

**Comment by JakeChampion** [comment]
Doing a search for the last month for ftbrand use and so far, nothing is using it 🎉  -- https://financialtimes.splunkcloud.com/en-GB/app/search/search?sid=1608050009.3068087

**Comment by JakeChampion** [comment]
Based on the results of the above search, we can safely deprecate this image-set entirely if we want to 🎉

**Comment by notlee** [comment]
Yes let's deprecate 👍 [some of the logos are likely out of date](https://docs.google.com/document/d/1ohsjo_sFCR2gyqc_eJNRMQrPrPGuYQr7RfViikVDrA0/). I think some were used on the app at one point but can't see the [life and arts logo on the life and arts page](https://app.ft.com/index_page/cover_life_arts_home), so maybe they're just not used now in digital products (as opposed to the app hosting their own version). We can always create a new image set if a need to share these logos appears.
